disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - fatal_error_message
included:
  - .
excluded:
  - Carthage
  - Pods
  - fastlane
reporter: "xcode"




